server {
    listen 8000;
    server_name localhost;
    root /root/workspace/moaz-carvalue.linkgrid.dev/public;
    index index.php;
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php-fpm/www.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    error_log /var/log/nginx/moaz-carvalue.error.log;
    access_log /var/log/nginx/moaz-carvalue.access.log;
}
